### ISSUE TITLE
Hot Start - time_org field

### ISSUE THREAD

**Issue by VishnuDevA7** [ImperialCollegeLondon/ICLOCS#11]
I am trying to initialize solving mymulti-phase NLP with a good initial guess and for the same I am trying to use the Hot start feature. Accordingly, I provided the states, inputs, time and multiplier fields for the guess variable from a previous solution. Even then I get an error as follows :
*******************************************************************************************
Reference to non-existent field 'time_org'.
Error in getGuessSolution (line 265)
                data.multipliers.lambda=interp1(guess.time_org, guess.multipliers.lambda,T,'linear');
Error in transcribeOCP_eachPhase (line 1368)
[ x_guess, u_guess, data ] = getGuessSolution( options, guess, problem, data );
Error in transcribeMultiphaseOCP (line 100)
    [phaseinfoNLP{i},phasedata{i},options.phaseoptions{i}]=transcribeOCP_eachPhase(problem.phases{i},guess.phases{i},options.phaseoptions{i});
Error in solveMyProblem (line 22)
            [infoNLP,data,options]=transcribeMultiphaseOCP(problem,guess,options);% Format for NLP solver
Error in main_ThreePhase (line 6)
[solution,MRHistory]=solveMyProblem( problem,guess,options); 
*******************************************************************************************
I could not find time_org filed in any of the structures that appear with the previous solution.

**Comment by VishnuDevA7** [comment]
The problem seems to go away if the previous solution is found meshstrategy - fixed option. So I am closing it.

**Comment by yuanbonie** [comment]
Hi Vishnu,

Thanks, sorry for the delayed reponse as my day was full. That was actually my oversight and I have made the update to allow you to supply the initial guess of multipliers without needing it to be in the mesh refinement framework. 

Cheers,
Yuanbo

**Comment by VishnuDevA7** [comment]
Thank you!
