### ISSUE TITLE
callbackFunction crashes MATLAB

### ISSUE THREAD

**Issue by VishnuDevA7** [ImperialCollegeLondon/ICLOCS#12]
I am running ICLOCS on MATLAB 2017b with Ipopt-3.12.10 MATLAB interface on Ubuntu 16.04. Whenever I try to use the callback functionality through ICLOCS, MATLAB crashes and I get an error on the terminal that runs the MATLAB process : "Segmentation fault (core dumped)". Even if the callback function does nothing but only return an output "true" , at the very first iteration, MATLAB crashes this way.

I tried to use the examplehs038.m file in "Ipopt-3.12.10/Ipopt/contrib/MatlabInterface/examples" path. This file has its own callback function where I am able to create breakpoints, print information, etc. It runs without any issue. 

Are you able to run callback function without any trouble on any example problem? I tried to run the same on CartPoleSwingUp problem using the template my_callback function. I still witness the same crash. Any suggestions ?

**Comment by yuanbonie** [comment]
Hi Vishnu,

Unfortunately I can not recreate this issues, however I am running under a Windows machine. Do you by chance have a Windows machine around to test it there?

Cheers,
Yuanbo

**Comment by VishnuDevA7** [comment]
I just figured the problem is with my version of IPOPT. I came across online that with IPOPT-3.12.12, the problem goes away. However, I am unable to find an installable MATLAB interface for this version. Further, the problem does not arise when I run the examples that is within the MATLAB interface with callbacks, this is confusing. 

I currently do not have a chance to test it on the Windows interface.

**Comment by yuanbonie** [comment]
Hi Vishnu,

Unfortunately due to COVID19, I do not have access to any linux machines for testing. 

I suspect the example problem calls ipopt(...) where ICLOCS calls ipopt_auxdata(...), which is required to pass on the necessary information. Chould you help me confirm this? Thanks!

**Comment by VishnuDevA7** [comment]
Yes, you are right. However, I compared the function calls to ipopt in both cases ("examplehs038" as well as "ipopt_auxdata") and all the fields in the structure ("funcs" in the case of "examplehs038" and "funcs_new" on the case of "ipopt_auxdata") look similar. However, the callback in ipopt_auxdata is linked by two handle levels : 
funcs_new.iterfunc: @(t,f,varstruct)funcs.iterfunc(t,f,auxdata)

funcs.iterfunc: @my_callback


This is the only visible difference. I am not sure if this is what causes the error though.

**Comment by yuanbonie** [comment]
Maybe give problem.callback=@(t,f,varstruct)callback_myProblem a try? For me both syntax works

**Comment by VishnuDevA7** [comment]
No, MATLAB still crashes with the same error on having problem.callback=@(t,f,varstruct)callback_myProblem.

**Comment by VishnuDevA7** [comment]
I still do not have an explanation, however, when I changed the name of the global variable from "sol" to something else, the problem disappears.
