### ISSUE TITLE
hessian_AN_F undefined e2 variable

### ISSUE THREAD

**Issue by maximiliano1985** [ImperialCollegeLondon/ICLOCS#14]
It seems that variable **e2** in function hessian_AN_F is never defined but used in lines 44 and 50.
Is this a typo and should be **e** instead of **e2**?

**Comment by yuanbonie** [comment]
Thanks for the note. They are two different variables but the function handle should have e2 included. Fixed in the latest github version

**Comment by maximiliano1985** [comment]
Ah ok, I just replaced e2 with e and saw that the results I was obtaining with the analytical derivatives was very similar to the one I obtained with the numerical derivatives (but this might be due to the fact that my problem has a simple formulation).
Has the new release been scheduled? Is there a release plan?

**Comment by yuanbonie** [comment]
Feel free to use the latest GitHub version, which has the problem fixed. I personally do not work much with analytical derivatives, therefore please let me know if you encountered more issues. Thanks in advance 👍

**Comment by maximiliano1985** [comment]
Sorry I just saw the message today. Thanks a lot for fixing the problem. I've been using Iclocs2 as primary OCP library for more than 6 years and I love it. The work you are doing is amazing.
Thanks
