### ISSUE TITLE
Undefined function or variable 'ipopt_auxdata'

### ISSUE THREAD

**Issue by kunpengyao** [ImperialCollegeLondon/ICLOCS#19]
Hello, I am interested in using this package. However, I received error message when testing examples regarding the following line:

https://github.com/ImperialCollegeLondon/ICLOCS/blob/bc6d581771d02d52c2aa1a21e8001231353c9368/src/problemTranscriptionSolve/solveSingleNLP_DirectCollocation.m#L54

Are there any dependencies should be installed?

**Comment by DengYaosheng** [comment]
Undefined function or variable 'ipopt_auxdata'

I also have this problem now. Could you tell me how to solve it ?

Thanks a lot

**Comment by yuanbonie** [comment]
Dear Yaosheng,

The issue is related to IPOPT not being correctly installed. The easiest way to install now is simply from Matlab's add-ons manager.

Hope this helps.

Best,
Yuanbo
________________________________
