### ISSUE TITLE
WORHP and fmincon NLP solvers not working

### ISSUE THREAD

**Issue by stumarcus314** [ImperialCollegeLondon/ICLOCS#2]
I get the following MATLAB errors when I run   ICLOCS-master\exampleProblems\BatchFermentor\ main_Auto_MeshRefinement.m, having changed the NLP solver to worhp or fmincon.

WORHP ERROR:

>> main_Auto_MeshRefinement
Transforming User Function: 'BatchFermentorPlant'
    Taking Derivatives wrt: 'Y, 'T...
Printing derivatives to file 'dynamics_Y'
Successfully transformed user function 'BatchFermentorPlant' to derivative function 'dynamics_Y'
Total file generation time: 3.571
Transforming User Function: 'dynamics_Y'
    Taking Derivatives wrt: 'Y, 'T...
Printing derivatives to file 'dynamics_YY'
Successfully transformed user function 'dynamics_Y' to derivative function 'dynamics_YY'
Total file generation time: 2.7416
Determine sparsity structure
Formatting matrices for the hermite-simpson approximation
Generate finite-difference pertubation vectors
Error using worhp
Incorrect number of input arguments
Error in solveNLP (line 152)
        dataworhp = worhp('worhp.xml');
Error in main_Auto_MeshRefinement (line 37)
    [solution,infoNLP1,data] = solveNLP(infoNLP,data);      % Solve the NLP

fmincon ERROR:

>> main_h_MeshRefinement
Determine sparsity structure
Formatting matrices for the hermite-simpson approximation
Generate finite-difference pertubation vectors
WARNING: Use of fmincon is NOT ADVISABLE because the solution speed can be significantly slower with a higher chance of failure. 
 We would recommend to use fmincon only for sanity checks. 
 For solving, please consider use IPOPT (see http://www.ee.ic.ac.uk/ICLOCS/Downloads.html). 
 Press any key to continue...
 
Reference to non-existent field 'fmincon'.
Error in solveNLP (line 87)
            [],[],[],[],NLP.zl,NLP.zu,@(z)fminConst(z,data,NLP),data.options.fmincon);
Error in main_h_MeshRefinement (line 38)
    [solution,infoNLP1,data] = solveNLP(infoNLP,data);      % Solve the NLP

**Comment by AdamGhannam** [comment]
What was the solution?
