### ISSUE TITLE
Named Figures in genSolutionPlots instead of indeces

### ISSUE THREAD

**Issue by kswannet** [ImperialCollegeLondon/ICLOCS#20]
In genSolutionPlots, figures are now created by calling "figure(1)", "figure(2)", etc. which can overwrite or add to figure created outside ICLOCS. Creating the figures using names, e.g. "figure('Name','States')" or "statesFig = figure('Name','States')", could avoid conflicting figures.

**Comment by yuanbonie** [comment]
Thank you. The change has been made in the latest version.
