### ISSUE TITLE
Error when providing analytic constraint jacobian

### ISSUE THREAD

**Issue by radiodawn5** [ImperialCollegeLondon/ICLOCS#3]
When providing analytic constraint jacobian ("dg.flag=1"), the below exceptions are thrown. After I addressed this error by passing `dg` to `jacConst_AN_G`, further runtime errors related to size of nt remain. The inequality constrains in my problem are independent of t, p and u. Only depend on x.
```
Undefined variable "dg" or class "dg.dx".
Error in jacConst_AN_G (line 6)
    dgz=[dg.dx dg.du];
Error in jacConstz (line 47)
    [ gz ] = jacConst_AN_G( gz, M, nt, np, ng, nz, T, data );
Error in directCollocation (line 165)
                [sol{phaseNo}.jacConst,sol{phaseNo}.Jf]=jacConstz(df,dg,g,f,avrc,X,U,P,tau,db,b,x0,xf,u0,uf,p,t0,tf,data);
Error in constraintJacobian (line 56)
                 jacConst=directCollocation('jacConst',z,data,1);
Error in ipopt_auxdata>@(x)funcs.jacobian(x,auxdata) (line 22)
        funcs_new.jacobian = @(x) funcs.jacobian(x, auxdata);
```

**Comment by yuanbonie** [comment]
Thanks for the info. I have updated the code. Hopefully the problem is now resolved. 

Apart from a few examples, I do not really use analytic derivatives for myself. Please let me know if you encounter further issues and we can resolve them together. Many thanks!
