### ISSUE TITLE
solveMyProblem issue

### ISSUE THREAD

**Issue by VishnuDevA7** [ImperialCollegeLondon/ICLOCS#6]
Hi, in line 25 of solveMyProblem.m, the option data structure misses out some fields (specifically "resultRep") when solving a  multi-phase problem with a fixed mesh. Due to this, the program throws an error, and does not execute runPostSolveTasks.m for post-processing. You can try to replicate this error by changing the options.meshstrategy to "fixed" in the settings_BangBangTwoPhase.m file and run main_BangbangTwoPhase.m .

**Comment by yuanbonie** [comment]
Many thanks! I have solved the error and please update to latest code and let me know for further issues.

**Comment by VishnuDevA7** [comment]
Yep, it works correctly now.
